// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OBS_Net.DAL.ORM.EFCore;

namespace OBS_Net.DAL.Migrations
{
    [DbContext(typeof(ObsContext))]
    [Migration("20191219160814_first-2")]
    partial class first2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OBS_Net.Entities.Tables.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("Tbl_Lessons","Obs");
                });

            modelBuilder.Entity("OBS_Net.Entities.Tables.LessonForStudent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("LessonId");

                    b.Property<Guid?>("StudentId");

                    b.Property<Guid?>("TeacherId");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Tbl_Lessons_Student","Obs");
                });

            modelBuilder.Entity("OBS_Net.Entities.Tables.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Grade");

                    b.Property<bool>("IsActive");

                    b.Property<string>("NameSurname")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<DateTime>("RegisterDate");

                    b.Property<string>("StudentNu");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Students","Obs");
                });

            modelBuilder.Entity("OBS_Net.Entities.Tables.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NameSurname")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Tag")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Tbl_Teacher","Obs");
                });

            modelBuilder.Entity("OBS_Net.Entities.Tables.LessonForStudent", b =>
                {
                    b.HasOne("OBS_Net.Entities.Tables.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId");

                    b.HasOne("OBS_Net.Entities.Tables.Student", "Student")
                        .WithMany("MyLessons")
                        .HasForeignKey("StudentId");

                    b.HasOne("OBS_Net.Entities.Tables.Teacher", "Teacher")
                        .WithMany("MeLessons")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
